INSERT INTO burgers (burger_name) VALUES ("Bacon Cheesburger")
INSERT INTO burgers (devoured) VALUES (false)
INSERT INTO burgers (burger_name) VALUES ("Mushroom Burger")
INSERT INTO burgers (devoured) VALUES (false)
INSERT INTO burgers (burger_name) VALUES ("Pastrami Burger")
INSERT INTO burgers (devoured) VALUES (false)